# -*- coding: utf-8 -*-
"""Untitled21.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k2d1BTNB3d5wD3qkWk1Ws8QTfQass3qx
"""

pip install fpdf

from fpdf import FPDF

class PDF(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 12)
        self.cell(0, 10, 'Ashirbad Nayak', 0, 1, 'C')
        self.set_font('Arial', '', 10)
        self.cell(0, 10, 'ashirbad200nayak@gmail.com | +917978960350 | 7Mc 43, Cda-7, Cuttack, India', 0, 1, 'C')
        self.cell(0, 10, 'GitHub: https://github.com/ashirbad200nayak | LinkedIn: https://www.linkedin.com/in/ashirbad-nayak', 0, 1, 'C')
        self.ln(10)

    def chapter_title(self, title):
        self.set_font('Arial', 'B', 12)
        self.cell(0, 10, title, 0, 1, 'L')
        self.ln(2)

    def chapter_body(self, body):
        self.set_font('Arial', '', 10)
        self.multi_cell(0, 10, body)
        self.ln()

pdf = PDF()
pdf.add_page()

pdf.chapter_title('Objective')
pdf.chapter_body('Backend Engineer with expertise in Java, JavaScript, and Python development, seeking a role at Baker Hughes. Experienced in backend development, API design, automation, and troubleshooting, with a proven track record of collaborating with cross-functional teams.')

pdf.chapter_title('Skills')
pdf.chapter_body('Languages: JavaScript, Java, Python, HTML, CSS, MongoDB, C++\n'
                 'Frameworks: Node.js, Express.js, Spring Boot, Hibernate\n'
                 'Databases: MongoDB, MySQL, PostgreSQL\n'
                 'Tools: Docker, Jenkins, AWS, Git, RESTful APIs, Kubernetes, Grafana, Kibana, JIRA\n'
                 'Collaboration: Agile, Scrum, Kanban\n'
                 'Other: Linux commands, Shell scripting, Kafka, Troubleshooting')

pdf.chapter_title('Experience')
pdf.chapter_body('Spotline Inc, Bhubaneswar\n'
                 'Software Engineer\n'
                 'June 2023 - Present\n'
                 '- Developed backend services using Java and Node.js.\n'
                 '- Designed APIs with Express.js and Spring Boot.\n'
                 '- Managed data operations with MongoDB.\n'
                 '- Automated deployments using Jenkins and Docker on AWS.\n'
                 '- Utilized Kubernetes for cluster management and deployment.\n'
                 '- Monitored systems using Grafana and Kibana.\n\n'
                 'Dhabaleshwar Institute of Polytechnic, Cuttack\n'
                 'Web Development Intern\n'
                 'Jan 2022 - Apr 2022\n'
                 '- Built dynamic web pages with HTML, CSS, and JavaScript.\n'
                 '- Created RESTful APIs in PHP, managed MySQL databases.\n\n'
                 'BEYONDERS, Bhubaneswar\n'
                 'Web Development Intern\n'
                 'Mar 2022 - Jun 2022\n'
                 '- Developed backend for hotel website using Node.js.\n'
                 '- Built interactive features with JavaScript.')

pdf.chapter_title('Education')
pdf.chapter_body("Bachelor's in Technology in Computer Science and Information Technology\n"
                 'C.V. Raman Global University, May 2023')

pdf.chapter_title('Projects')
pdf.chapter_body('Veeva Vault Test Automation Tool\n'
                 '- Developed frontend with React, backend with Node.js and MongoDB.\n'
                 '- Automated tests with Robot Framework, deployed on Jenkins.\n\n'
                 'Dynamic College Website\n'
                 '- Developed website with HTML, CSS, JavaScript, and PHP.\n'
                 '- Managed data with MySQL.\n\n'
                 'Hotel Website\n'
                 '- Built backend with Node.js, interactive UI with HTML, CSS, JavaScript.')

pdf.chapter_title('Additional Skills')
pdf.chapter_body('Backend Development: Proficient in Java, JavaScript, Python.\n'
                 'API Design: Experienced in RESTful APIs.\n'
                 'Automation: Skilled in Jenkins, Docker, Robot Framework.\n'
                 'Collaboration: Effective in Agile environments.\n'
                 'Problem Solving: Strong critical thinking and attention to detail.\n'
                 'Communication: Excellent communication and collaboration skills, ability to work effectively in cross-functional teams.\n'
                 'Troubleshooting: Techniques and fixing customer issues on priority.')

pdf.output('Ashirbad_Nayak_Resume.pdf')